2019-11-23 18:07:04,029 [INFO] root consoleworker.py:439	Log file created
2019-11-23 18:07:04,030 [INFO] root consoleworker.py:443	Logging handler <logging.FileHandler object at 0x7fe788b831d0> added
2019-11-23 18:07:04,030 [INFO] root consoleworker.py:443	Logging handler <logging.StreamHandler object at 0x7fe79c0c0410> added
2019-11-23 18:07:04,030 [INFO] root consoleworker.py:443	Logging handler <logging.StreamHandler object at 0x7fe788bd2190> added
2019-11-23 18:07:04,030 [INFO] yandextank.core.tankcore tankcore.py:589	Lock file is found: /var/lock/lunapark_skqoAO.lock
2019-11-23 18:07:04,031 [DEBUG] root util.py:437	No process[3]: [Errno 3] No such process
2019-11-23 18:07:04,031 [INFO] yandextank.core.tankcore tankcore.py:599	Lock PID 8877 not exists, ignoring and trying to remove
2019-11-23 18:07:04,033 [INFO] root consoleworker.py:378	Created a folder for the test. /home/tsusho/stage-7/2019-highload-dht/logs/2019-11-23_18-07-03.989207
2019-11-23 18:07:04,034 [INFO] yandextank.core.tankcore tankcore.py:237	Configuring plugins...
2019-11-23 18:07:04,034 [INFO] yandextank.core.tankcore tankcore.py:190	Loading plugins...
2019-11-23 18:07:04,034 [DEBUG] yandextank.core.tankcore tankcore.py:192	Loading plugin phantom from yandextank.plugins.Phantom
2019-11-23 18:07:04,034 [DEBUG] yandextank.core.tankcore tankcore.py:192	Loading plugin rcheck from yandextank.plugins.ResourceCheck
2019-11-23 18:07:04,034 [DEBUG] yandextank.core.tankcore tankcore.py:192	Loading plugin json_report from yandextank.plugins.JsonReport
2019-11-23 18:07:04,034 [DEBUG] yandextank.core.tankcore tankcore.py:192	Loading plugin overload from yandextank.plugins.DataUploader
2019-11-23 18:07:04,035 [DEBUG] yandextank.core.tankcore tankcore.py:192	Loading plugin rcassert from yandextank.plugins.RCAssert
2019-11-23 18:07:04,035 [DEBUG] yandextank.core.tankcore tankcore.py:192	Loading plugin console from yandextank.plugins.Console
2019-11-23 18:07:04,035 [DEBUG] yandextank.core.tankcore tankcore.py:192	Loading plugin shellexec from yandextank.plugins.ShellExec
2019-11-23 18:07:04,035 [DEBUG] yandextank.core.tankcore tankcore.py:192	Loading plugin autostop from yandextank.plugins.Autostop
2019-11-23 18:07:04,035 [DEBUG] yandextank.core.tankcore tankcore.py:212	Plugin instances: {'plugin_phantom': <yandextank.plugins.Phantom.plugin.Plugin object at 0x7fe788b91350>, 'plugin_autostop': <yandextank.plugins.Autostop.plugin.Plugin object at 0x7fe78889a7d0>, 'plugin_shellexec': <yandextank.plugins.ShellExec.plugin.Plugin object at 0x7fe78889ac50>, 'plugin_console': <yandextank.plugins.Console.plugin.Plugin object at 0x7fe78889ad90>, 'plugin_rcassert': <yandextank.plugins.RCAssert.plugin.Plugin object at 0x7fe78889a2d0>, 'plugin_rcheck': <yandextank.plugins.ResourceCheck.plugin.Plugin object at 0x7fe7888eb910>, 'plugin_overload': <yandextank.plugins.DataUploader.plugin.Plugin object at 0x7fe78889a790>, 'plugin_json_report': <yandextank.plugins.JsonReport.plugin.Plugin object at 0x7fe7888eb8d0>}
2019-11-23 18:07:04,035 [DEBUG] yandextank.core.tankcore tankcore.py:244	Configuring <yandextank.plugins.Phantom.plugin.Plugin object at 0x7fe788b91350>
2019-11-23 18:07:04,036 [DEBUG] yandextank.core.tankcore tankcore.py:395	Searching for plugin: <class 'yandextank.plugins.Autostop.plugin.Plugin'>
2019-11-23 18:07:04,036 [DEBUG] yandextank.core.tankcore tankcore.py:450	Adding artifact file to collect (keep=False): /home/tsusho/stage-7/2019-highload-dht/logs/2019-11-23_18-07-03.989207/answ_s8Qkcb.log
2019-11-23 18:07:04,037 [DEBUG] yandextank.core.tankcore tankcore.py:450	Adding artifact file to collect (keep=False): /home/tsusho/stage-7/2019-highload-dht/logs/2019-11-23_18-07-03.989207/phout_IWZRrz.log
2019-11-23 18:07:04,037 [DEBUG] yandextank.core.tankcore tankcore.py:450	Adding artifact file to collect (keep=False): /home/tsusho/stage-7/2019-highload-dht/logs/2019-11-23_18-07-03.989207/phantom_stat_w50VPT.log
2019-11-23 18:07:04,037 [DEBUG] yandextank.core.tankcore tankcore.py:450	Adding artifact file to collect (keep=False): /home/tsusho/stage-7/2019-highload-dht/logs/2019-11-23_18-07-03.989207/phantom_kja488.log
2019-11-23 18:07:04,037 [DEBUG] yandextank.common.util util.py:488	Trying to resolve address string: 127.0.0.1:8080
2019-11-23 18:07:04,038 [DEBUG] yandextank.common.util util.py:525	Parsing port
2019-11-23 18:07:04,038 [DEBUG] yandextank.common.util util.py:536	Lookup result: [(2, 1, 6, '', ('127.0.0.1', 8080)), (2, 2, 17, '', ('127.0.0.1', 8080)), (2, 3, 0, '', ('127.0.0.1', 8080))]
2019-11-23 18:07:04,038 [INFO] yandextank.common.util util.py:555	Testing connection to resolved address 127.0.0.1 and port 8080
2019-11-23 18:07:04,039 [DEBUG] yandextank.common.util util.py:574	Exception on connect attempt [127.0.0.1]:8080 : Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/yandextank/common/util.py", line 570, in __test
    test_sock.connect(sa)
  File "/usr/lib/python2.7/socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
error: [Errno 111] Connection refused

2019-11-23 18:07:04,039 [INFO] yandextank.common.util util.py:558	Failed TCP connection test using [127.0.0.1]:8080
2019-11-23 18:07:04,039 [DEBUG] yandextank.common.util util.py:559	Failed TCP connection test using [127.0.0.1]:8080
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/yandextank/common/util.py", line 556, in resolve
    self.__test(family, (parsed_ip, port))
  File "/usr/local/lib/python2.7/dist-packages/yandextank/common/util.py", line 576, in __test
    raise RuntimeError(msg % (sa[0], sa[1]))
RuntimeError: TCP Connection test failed for [127.0.0.1]:8080, use phantom.connection_test=0 to disable it
2019-11-23 18:07:04,040 [INFO] yandextank.common.util util.py:555	Testing connection to resolved address 127.0.0.1 and port 8080
2019-11-23 18:07:04,040 [DEBUG] yandextank.common.util util.py:574	Exception on connect attempt [127.0.0.1]:8080 : Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/yandextank/common/util.py", line 570, in __test
    test_sock.connect(sa)
  File "/usr/lib/python2.7/socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
error: [Errno 111] Connection refused

2019-11-23 18:07:04,040 [INFO] yandextank.common.util util.py:558	Failed TCP connection test using [127.0.0.1]:8080
2019-11-23 18:07:04,041 [DEBUG] yandextank.common.util util.py:559	Failed TCP connection test using [127.0.0.1]:8080
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/yandextank/common/util.py", line 556, in resolve
    self.__test(family, (parsed_ip, port))
  File "/usr/local/lib/python2.7/dist-packages/yandextank/common/util.py", line 576, in __test
    raise RuntimeError(msg % (sa[0], sa[1]))
RuntimeError: TCP Connection test failed for [127.0.0.1]:8080, use phantom.connection_test=0 to disable it
2019-11-23 18:07:04,041 [INFO] yandextank.common.util util.py:555	Testing connection to resolved address 127.0.0.1 and port 8080
2019-11-23 18:07:04,041 [DEBUG] yandextank.common.util util.py:574	Exception on connect attempt [127.0.0.1]:8080 : Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/yandextank/common/util.py", line 570, in __test
    test_sock.connect(sa)
  File "/usr/lib/python2.7/socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
error: [Errno 111] Connection refused

2019-11-23 18:07:04,041 [INFO] yandextank.common.util util.py:558	Failed TCP connection test using [127.0.0.1]:8080
2019-11-23 18:07:04,041 [DEBUG] yandextank.common.util util.py:559	Failed TCP connection test using [127.0.0.1]:8080
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/yandextank/common/util.py", line 556, in resolve
    self.__test(family, (parsed_ip, port))
  File "/usr/local/lib/python2.7/dist-packages/yandextank/common/util.py", line 576, in __test
    raise RuntimeError(msg % (sa[0], sa[1]))
RuntimeError: TCP Connection test failed for [127.0.0.1]:8080, use phantom.connection_test=0 to disable it
2019-11-23 18:07:04,042 [ERROR] root consoleworker.py:267	Exception occurred:
<type 'exceptions.RuntimeError'>: All connection attempts failed for 127.0.0.1, use {phantom.connection_test: false} to disable it
  File "/usr/local/lib/python2.7/dist-packages/yandextank/core/consoleworker.py", line 380, in run
    self.core.plugins_configure()

  File "/usr/local/lib/python2.7/dist-packages/yandextank/core/tankcore.py", line 245, in plugins_configure
    plugin.configure()

  File "/usr/local/lib/python2.7/dist-packages/yandextank/plugins/Phantom/plugin.py", line 73, in configure
    self.phantom_config = self.phantom.config_file

  File "/usr/local/lib/python2.7/dist-packages/yandextank/plugins/Phantom/plugin.py", line 82, in phantom
    self._phantom.read_config()

  File "/usr/local/lib/python2.7/dist-packages/yandextank/plugins/Phantom/utils.py", line 95, in read_config
    stream.read_config()

  File "/usr/local/lib/python2.7/dist-packages/yandextank/plugins/Phantom/utils.py", line 275, in read_config
    self.address, do_test_connect, explicit_port)

  File "/usr/local/lib/python2.7/dist-packages/yandextank/common/util.py", line 564, in resolve
    raise RuntimeError(msg % address_str)

2019-11-23 18:07:04,042 [INFO] root consoleworker.py:268	Trying to clean up
2019-11-23 18:07:04,042 [INFO] yandextank.core.tankcore tankcore.py:565	Releasing lock: /var/lock/lunapark_sdQDKZ.lock
2019-11-23 18:07:04,043 [WARNING] root consoleworker.py:413	Job number is not available yet
2019-11-23 18:07:04,043 [WARNING] root consoleworker.py:420	Job number is not available yet
2019-11-23 18:07:04,046 [DEBUG] yandextank.core.tankcore tankcore.py:371	Collecting artifacts
2019-11-23 18:07:04,046 [INFO] yandextank.core.tankcore tankcore.py:372	Artifacts dir: /home/tsusho/stage-7/2019-highload-dht/logs/2019-11-23_18-07-03.989207
2019-11-23 18:07:04,046 [DEBUG] yandextank.core.tankcore tankcore.py:426	Collecting file: /home/tsusho/stage-7/2019-highload-dht/logs/2019-11-23_18-07-03.989207/phantom_stat_w50VPT.log to /home/tsusho/stage-7/2019-highload-dht/logs/2019-11-23_18-07-03.989207/phantom_stat_w50VPT.log
2019-11-23 18:07:04,046 [WARNING] yandextank.core.tankcore tankcore.py:433	File already exists: /home/tsusho/stage-7/2019-highload-dht/logs/2019-11-23_18-07-03.989207/phantom_stat_w50VPT.log
2019-11-23 18:07:04,047 [DEBUG] yandextank.core.tankcore tankcore.py:426	Collecting file: validation_error.yaml to /home/tsusho/stage-7/2019-highload-dht/logs/2019-11-23_18-07-03.989207/validation_error.yaml
2019-11-23 18:07:04,047 [WARNING] yandextank.core.tankcore tankcore.py:428	File not found to collect: validation_error.yaml
2019-11-23 18:07:04,047 [DEBUG] yandextank.core.tankcore tankcore.py:426	Collecting file: /home/tsusho/stage-7/2019-highload-dht/logs/2019-11-23_18-07-03.989207/answ_s8Qkcb.log to /home/tsusho/stage-7/2019-highload-dht/logs/2019-11-23_18-07-03.989207/answ_s8Qkcb.log
2019-11-23 18:07:04,047 [WARNING] yandextank.core.tankcore tankcore.py:433	File already exists: /home/tsusho/stage-7/2019-highload-dht/logs/2019-11-23_18-07-03.989207/answ_s8Qkcb.log
2019-11-23 18:07:04,047 [DEBUG] yandextank.core.tankcore tankcore.py:426	Collecting file: /home/tsusho/stage-7/2019-highload-dht/logs/2019-11-23_18-07-03.989207/phantom_kja488.log to /home/tsusho/stage-7/2019-highload-dht/logs/2019-11-23_18-07-03.989207/phantom_kja488.log
2019-11-23 18:07:04,047 [WARNING] yandextank.core.tankcore tankcore.py:433	File already exists: /home/tsusho/stage-7/2019-highload-dht/logs/2019-11-23_18-07-03.989207/phantom_kja488.log
2019-11-23 18:07:04,047 [DEBUG] yandextank.core.tankcore tankcore.py:426	Collecting file: /home/tsusho/stage-7/2019-highload-dht/logs/2019-11-23_18-07-03.989207/phout_IWZRrz.log to /home/tsusho/stage-7/2019-highload-dht/logs/2019-11-23_18-07-03.989207/phout_IWZRrz.log
2019-11-23 18:07:04,047 [WARNING] yandextank.core.tankcore tankcore.py:433	File already exists: /home/tsusho/stage-7/2019-highload-dht/logs/2019-11-23_18-07-03.989207/phout_IWZRrz.log
